// Per-theatre live-wire configs. One entry per site theatre except ukraine
// (which keeps its own collector + gazetteer). All sources keyless except
// ReliefWeb (free approved appname, same secret as ukraine).
// Feeds verified live 2026-09-24 (HTTP 200 + items parsed). GDELT FIPS 10-4
// codes; gazetteer coords are major-city reference points (approximate tier).

const gnews = (id, theatre, query) => ({
  id,
  theatre,
  name: 'Google News',
  url: 'https://news.google.com/rss/search?q=' + encodeURIComponent(query) + '&hl=en-US&gl=US&ceid=US%3Aen',
  outletFromSourceTag: true,
});

export const THEATRES = {
  taiwan: {
    id: 'taiwan',
    dir: 'taiwan-events',
    gdelt: { fips: ['TW'], defaultGeo: 'Taiwan' },
    actorMap: [
      ['TAIWAN|TAIPEI', 'Taiwan'],
      ['CHINA|CHINESE|BEIJING|PLA', 'China'],
      ['UNITED STATES|U\\.S\\.|WASHINGTON|PENTAGON', 'United States'],
    ],
    rssFeeds: [
      {
        id: 'taipei-times', theatre: 'taiwan', name: 'Taipei Times', url: 'https://www.taipeitimes.com/xml/index.rss',
        match: ['TAIWAN', 'TAIPEI', 'CROSS-?STRAIT', 'STRAIT', 'PLA', 'KINMEN', 'MATSU', 'PENGHU', 'TSMC', 'SEMICONDUCTOR', 'KUOMINTANG', 'CHINA', 'CHINESE', 'BEIJING', 'INVASION', 'DRILL', 'TAOYUAN', 'HSINCHU', 'TAICHUNG', 'TAINAN', 'KAOHSIUNG', 'KEELUNG', 'HUALIEN', 'CHIAYI'],
      },
      gnews('gnews-strait', 'taiwan', 'Taiwan Strait China PLA'),
      gnews('gnews-defense', 'taiwan', 'Taiwan PLA military drills'),
    ],
    reliefwebIso3: ['twn'],
    osm: { countryCodes: ['tw', 'cn'], bbox: [20.5, 116.5, 27.5, 124.5] },
    outletsToStrip: ['Taipei Times'],
    gazetteer: [
      { names: ['Taipei'], lat: 25.03, lng: 121.57, label: 'Taipei', level: 'city', capital: true },
      { names: ['Kaohsiung'], lat: 22.63, lng: 120.31, label: 'Kaohsiung', level: 'city' },
      { names: ['Taichung'], lat: 24.14, lng: 120.68, label: 'Taichung', level: 'city' },
      { names: ['Tainan'], lat: 22.99, lng: 120.23, label: 'Tainan', level: 'city' },
      { names: ['Taoyuan'], lat: 24.99, lng: 121.31, label: 'Taoyuan', level: 'city' },
      { names: ['Hsinchu'], lat: 24.81, lng: 120.97, label: 'Hsinchu', level: 'city' },
      { names: ['Keelung', 'Jilong'], lat: 25.13, lng: 121.74, label: 'Keelung', level: 'city' },
      { names: ['Chiayi'], lat: 23.48, lng: 120.45, label: 'Chiayi', level: 'city' },
      { names: ['Hualien'], lat: 23.97, lng: 121.6, label: 'Hualien', level: 'city' },
      { names: ['Kinmen', 'Quemoy'], lat: 24.44, lng: 118.33, label: 'Kinmen', level: 'city' },
      { names: ['Matsu'], lat: 26.16, lng: 119.95, label: 'Matsu', level: 'city' },
      { names: ['Penghu', 'Pescadores'], lat: 23.57, lng: 119.59, label: 'Penghu', level: 'city' },
      { names: ['Taiwan Strait'], lat: 24.5, lng: 119.5, label: 'Taiwan Strait', level: 'region' },
    ],
  },
  gaza: {
    id: 'gaza',
    dir: 'gaza-events',
    gdelt: { fips: ['GZ', 'WE', 'IS'], defaultGeo: 'Gaza' },
    actorMap: [
      ['ISRAEL|IDF|TEL AVIV|NETANYAHU', 'Israel'],
      ['HAMAS|GAZA|PALESTIN', 'Palestinians'],
      ['HEZBOLLAH', 'Hezbollah'],
      ['UNITED STATES|U\\.S\\.', 'United States'],
    ],
    rssFeeds: [
      { id: 'bbc-me', theatre: 'gaza', name: 'BBC', url: 'https://feeds.bbci.co.uk/news/world/middle_east/rss.xml' },
      {
        id: 'jpost', theatre: 'gaza', name: 'Jerusalem Post', url: 'https://www.jpost.com/rss/rssfeedsfrontpage.aspx',
        match: ['IDF', 'GAZA', 'HAMAS', 'NETANYAHU', 'ISRAEL', 'JERUSALEM', 'TEL AVIV', 'WEST BANK', 'HEZBOLLAH', 'HOSTAGE', 'CEASEFIRE', 'PALESTIN', 'HOUTHI', 'KNESSET', 'RAFAH', 'JENIN', 'NABLUS', 'RAMALLAH', 'HEBRON', 'BEERSHEBA', 'ASHKELON', 'SDEROT', 'HAIFA', 'EILAT', 'LEBANON', 'SYRIA'],
      },
      gnews('gnews-gaza', 'gaza', 'Gaza Israel Hamas'),
      gnews('gnews-ceasefire', 'gaza', 'Gaza ceasefire hostages aid'),
    ],
    reliefwebIso3: ['pse', 'isr'],
    osm: { countryCodes: ['ps', 'il'], bbox: [29.0, 32.0, 34.0, 37.0] },
    outletsToStrip: [],
    gazetteer: [
      { names: ['Gaza City', 'Gaza'], lat: 31.5, lng: 34.47, label: 'Gaza City', level: 'city' },
      { names: ['Rafah'], lat: 31.29, lng: 34.24, label: 'Rafah', level: 'city' },
      { names: ['Khan Younis', 'Khan Yunis'], lat: 31.34, lng: 34.31, label: 'Khan Younis', level: 'city' },
      { names: ['Jabalia', 'Jabaliya'], lat: 31.53, lng: 34.48, label: 'Jabalia', level: 'city' },
      { names: ['Deir al-Balah', 'Deir al Balah'], lat: 31.42, lng: 34.35, label: 'Deir al-Balah', level: 'city' },
      { names: ['Beit Hanoun'], lat: 31.54, lng: 34.53, label: 'Beit Hanoun', level: 'city' },
      { names: ['Nuseirat'], lat: 31.45, lng: 34.39, label: 'Nuseirat', level: 'city' },
      { names: ['Ramallah'], lat: 31.9, lng: 35.2, label: 'Ramallah', level: 'city' },
      { names: ['Nablus'], lat: 32.22, lng: 35.26, label: 'Nablus', level: 'city' },
      { names: ['Jenin'], lat: 32.46, lng: 35.29, label: 'Jenin', level: 'city' },
      { names: ['Hebron'], lat: 31.53, lng: 35.09, label: 'Hebron', level: 'city' },
      { names: ['Jerusalem'], lat: 31.77, lng: 35.21, label: 'Jerusalem', level: 'city', capital: true },
      { names: ['Tel Aviv'], lat: 32.08, lng: 34.78, label: 'Tel Aviv', level: 'city' },
      { names: ['Ashkelon'], lat: 31.67, lng: 34.57, label: 'Ashkelon', level: 'city' },
      { names: ['Sderot'], lat: 31.52, lng: 34.59, label: 'Sderot', level: 'city' },
      { names: ['Haifa'], lat: 32.82, lng: 34.99, label: 'Haifa', level: 'city' },
      { names: ['West Bank'], lat: 31.9, lng: 35.25, label: 'West Bank', level: 'region' },
    ],
  },
  iran: {
    id: 'iran',
    dir: 'iran-events',
    gdelt: { fips: ['IR'], defaultGeo: 'Iran' },
    actorMap: [
      ['IRAN|TEHRAN|IRGC|KHAMENEI', 'Iran'],
      ['ISRAEL|IDF', 'Israel'],
      ['UNITED STATES|U\\.S\\.|WASHINGTON', 'United States'],
      ['HOUTHI|YEMEN', 'Houthis'],
    ],
    rssFeeds: [
      gnews('gnews-iran', 'iran', 'Iran Hormuz nuclear'),
      gnews('gnews-unrest', 'iran', 'Iran protests Khamenei'),
      gnews('gnews-policy', 'iran', 'Tehran sanctions oil'),
    ],
    reliefwebIso3: ['irn'],
    osm: { countryCodes: ['ir'], bbox: [24.0, 43.0, 41.0, 65.0] },
    outletsToStrip: [],
    gazetteer: [
      { names: ['Tehran'], lat: 35.69, lng: 51.39, label: 'Tehran', level: 'city', capital: true },
      { names: ['Karaj'], lat: 35.84, lng: 51.0, label: 'Karaj', level: 'city' },
      { names: ['Isfahan', 'Esfahan'], lat: 32.65, lng: 51.68, label: 'Isfahan', level: 'city' },
      { names: ['Natanz'], lat: 33.51, lng: 51.92, label: 'Natanz', level: 'city' },
      { names: ['Fordow', 'Fordow'], lat: 34.88, lng: 50.99, label: 'Fordow', level: 'city' },
      { names: ['Qom'], lat: 34.64, lng: 50.88, label: 'Qom', level: 'city' },
      { names: ['Tabriz'], lat: 38.08, lng: 46.29, label: 'Tabriz', level: 'city' },
      { names: ['Mashhad'], lat: 36.26, lng: 59.62, label: 'Mashhad', level: 'city' },
      { names: ['Shiraz'], lat: 29.59, lng: 52.59, label: 'Shiraz', level: 'city' },
      { names: ['Ahvaz', 'Ahwaz'], lat: 31.32, lng: 48.69, label: 'Ahvaz', level: 'city' },
      { names: ['Bushehr'], lat: 28.92, lng: 50.83, label: 'Bushehr', level: 'city' },
      { names: ['Bandar Abbas'], lat: 27.19, lng: 56.27, label: 'Bandar Abbas', level: 'city' },
      { names: ['Kermanshah'], lat: 34.31, lng: 47.06, label: 'Kermanshah', level: 'city' },
      { names: ['Urmia'], lat: 37.55, lng: 45.07, label: 'Urmia', level: 'city' },
      { names: ['Strait of Hormuz', 'Hormuz Strait'], lat: 26.57, lng: 56.25, label: 'Strait of Hormuz', level: 'region' },
    ],
  },
  sahel: {
    id: 'sahel',
    dir: 'sahel-events',
    gdelt: { fips: ['ML', 'UV', 'NG'], defaultGeo: 'Sahel' },
    actorMap: [
      ['MALI|BAMAKO|JUNTA', 'Mali'],
      ['BURKINA|OUAGADOUGOU', 'Burkina Faso'],
      ['NIGER|NIAMEY', 'Niger'],
      ['RUSSIA|WAGNER|AFRICA CORPS', 'Russia / Africa Corps'],
      ['FRANCE|FRENCH', 'France'],
      ['UNITED STATES|U\\.S\\.|AFRICOM', 'United States'],
      ['JNIM|AL QAEDA|QAEDA|ISLAMIC STATE|ISIS|ISGS|ISWAP|BOKO', 'Jihadist groups'],
    ],
    rssFeeds: [
      { id: 'aa-mali', theatre: 'sahel', name: 'AllAfrica Mali', url: 'https://allafrica.com/tools/headlines/rdf/mali/headlines.rdf' },
      { id: 'aa-burkina', theatre: 'sahel', name: 'AllAfrica Burkina Faso', url: 'https://allafrica.com/tools/headlines/rdf/burkinafaso/headlines.rdf' },
      { id: 'aa-niger', theatre: 'sahel', name: 'AllAfrica Niger', url: 'https://allafrica.com/tools/headlines/rdf/niger/headlines.rdf' },
      gnews('gnews-sahel', 'sahel', 'Sahel Mali Burkina Niger'),
    ],
    reliefwebIso3: ['mli', 'bfa', 'ner'],
    osm: { countryCodes: ['ml', 'bf', 'ne'], bbox: [7.0, -19.0, 26.0, 39.0] },
    outletsToStrip: [],
    gazetteer: [
      { names: ['Bamako'], lat: 12.64, lng: -8.0, label: 'Bamako', level: 'city', capital: true },
      { names: ['Gao'], lat: 16.27, lng: -0.04, label: 'Gao', level: 'city' },
      { names: ['Kidal'], lat: 18.44, lng: 1.41, label: 'Kidal', level: 'city' },
      { names: ['Timbuktu', 'Tombouctou'], lat: 16.77, lng: -3.0, label: 'Timbuktu', level: 'city' },
      { names: ['Mopti'], lat: 14.49, lng: -4.2, label: 'Mopti', level: 'city' },
      { names: ['Menaka', 'Ménaka'], lat: 15.92, lng: 2.4, label: 'Menaka', level: 'city' },
      { names: ['Tessalit'], lat: 20.2, lng: 1.0, label: 'Tessalit', level: 'city' },
      { names: ['Ouagadougou'], lat: 12.37, lng: -1.53, label: 'Ouagadougou', level: 'city', capital: true },
      { names: ['Kaya'], lat: 13.09, lng: -1.08, label: 'Kaya', level: 'city' },
      { names: ['Djibo'], lat: 14.1, lng: -1.63, label: 'Djibo', level: 'city' },
      { names: ['Dori'], lat: 14.03, lng: -0.03, label: 'Dori', level: 'city' },
      { names: ['Ouahigouya'], lat: 13.58, lng: -2.42, label: 'Ouahigouya', level: 'city' },
      { names: ['Niamey'], lat: 13.51, lng: 2.11, label: 'Niamey', level: 'city', capital: true },
      { names: ['Agadez'], lat: 16.97, lng: 7.99, label: 'Agadez', level: 'city' },
      { names: ['Tillaberi', 'Tillabéri'], lat: 14.21, lng: 1.45, label: 'Tillaberi', level: 'city' },
      { names: ['Diffa'], lat: 13.32, lng: 12.62, label: 'Diffa', level: 'city' },
      { names: ['Tahoua'], lat: 14.89, lng: 5.27, label: 'Tahoua', level: 'city' },
    ],
  },
  korea: {
    id: 'korea',
    dir: 'korea-events',
    gdelt: { fips: ['KN', 'KS'], defaultGeo: 'Korea' },
    actorMap: [
      ['NORTH KOREA|DPRK|PYONGYANG|KIM JONG', 'North Korea'],
      ['SOUTH KOREA|\\bROK\\b|SEOUL|LEE JAE', 'South Korea'],
      ['UNITED STATES|U\\.S\\.', 'United States'],
      ['CHINA|BEIJING', 'China'],
    ],
    rssFeeds: [
      { id: 'yna-nk', theatre: 'korea', name: 'Yonhap', url: 'https://en.yna.co.kr/RSS/nk.xml' },
      {
        id: 'yna-news', theatre: 'korea', name: 'Yonhap', url: 'https://en.yna.co.kr/RSS/news.xml',
        match: ['KOREA', 'SEOUL', 'PYONGYANG', 'MISSILE', 'DMZ', 'NUCLEAR', 'KIM', 'KAESONG', 'WONSAN', 'BUSAN', 'INCHEON', 'PYEONGTAEK', 'OSAN', 'DAEGU', 'TAEGU', 'JEJU', 'JCS', 'Yoon', 'DEFECTOR', 'ABDUCTEE'],
      },
      {
        id: 'korea-times', theatre: 'korea', name: 'Korea Times', url: 'https://feed.koreatimes.co.kr/k/allnews.xml',
        match: ['KOREA', 'SEOUL', 'PYONGYANG', 'MISSILE', 'DMZ', 'NUCLEAR', 'KIM', 'KAESONG', 'WONSAN', 'BUSAN', 'INCHEON', 'PYEONGTAEK', 'OSAN', 'DAEGU', 'TAEGU', 'JEJU', 'JCS', 'Yoon', 'DEFECTOR', 'ABDUCTEE'],
      },
      gnews('gnews-korea', 'korea', 'North Korea missile Kim'),
    ],
    reliefwebIso3: ['prk', 'kor'],
    osm: { countryCodes: ['kp', 'kr'], bbox: [33.0, 122.0, 44.0, 133.5] },
    outletsToStrip: [],
    gazetteer: [
      { names: ['Pyongyang'], lat: 39.03, lng: 125.75, label: 'Pyongyang', level: 'city', capital: true },
      { names: ['Seoul'], lat: 37.57, lng: 126.98, label: 'Seoul', level: 'city', capital: true },
      { names: ['Kaesong'], lat: 37.97, lng: 126.55, label: 'Kaesong', level: 'city' },
      { names: ['Wonsan'], lat: 39.15, lng: 127.45, label: 'Wonsan', level: 'city' },
      { names: ['Hamhung'], lat: 39.92, lng: 127.53, label: 'Hamhung', level: 'city' },
      { names: ['Chongjin'], lat: 41.78, lng: 129.72, label: 'Chongjin', level: 'city' },
      { names: ['Nampo'], lat: 38.73, lng: 125.41, label: 'Nampo', level: 'city' },
      { names: ['Sinuiju'], lat: 40.11, lng: 124.4, label: 'Sinuiju', level: 'city' },
      { names: ['Panmunjom', 'Panmunjeom'], lat: 38.32, lng: 126.9, label: 'Panmunjom', level: 'city' },
      { names: ['Busan', 'Pusan'], lat: 35.18, lng: 129.08, label: 'Busan', level: 'city' },
      { names: ['Incheon', 'Inchon'], lat: 37.46, lng: 126.71, label: 'Incheon', level: 'city' },
      { names: ['Pyeongtaek'], lat: 36.99, lng: 126.83, label: 'Pyeongtaek', level: 'city' },
      { names: ['Osan'], lat: 37.15, lng: 127.08, label: 'Osan', level: 'city' },
      { names: ['Daegu', 'Taegu'], lat: 35.87, lng: 128.6, label: 'Daegu', level: 'city' },
      { names: ['DMZ', 'Demilitarized Zone'], lat: 38.32, lng: 127.0, label: 'DMZ', level: 'region' },
    ],
  },
  arctic: {
    id: 'arctic',
    dir: 'arctic-events',
    // No single FIPS: polar bbox over the site's theatre envelope instead.
    gdelt: { bbox: [58.0, -75.0, 84.0, 35.0], defaultGeo: 'Arctic' },
    actorMap: [
      ['RUSSIA|RUSSIAN|MOSCOW', 'Russia'],
      ['UNITED STATES|U\\.S\\.|WASHINGTON', 'United States'],
      ['CHINA|BEIJING', 'China'],
      ['GREENLAND|NUUK|DENMARK|DANISH', 'Greenland / Denmark'],
      ['NORWAY|OSLO', 'Norway'],
      ['CANADA|OTTAWA', 'Canada'],
    ],
    rssFeeds: [
      { id: 'rci-arctic', theatre: 'arctic', name: 'Eye on the Arctic', url: 'https://www.rcinet.ca/eye-on-the-arctic/feed/' },
      { id: 'nunatsiaq', theatre: 'arctic', name: 'Nunatsiaq News', url: 'https://nunatsiaq.com/feed/' },
      gnews('gnews-arctic', 'arctic', 'Arctic Greenland'),
    ],
    reliefwebIso3: null, // multi-country polar region; RSS covers it
    osm: { countryCodes: ['ca', 'gl', 'no', 'se', 'fi', 'is', 'ru', 'us'], bbox: [55.0, -180.0, 85.0, 60.0] },
    outletsToStrip: [],
    gazetteer: [
      { names: ['Nuuk'], lat: 64.18, lng: -51.72, label: 'Nuuk', level: 'city' },
      { names: ['Ilulissat'], lat: 69.22, lng: -51.1, label: 'Ilulissat', level: 'city' },
      { names: ['Pituffik', 'Thule'], lat: 76.53, lng: -68.83, label: 'Pituffik', level: 'city' },
      { names: ['Longyearbyen'], lat: 78.22, lng: 15.63, label: 'Longyearbyen', level: 'city' },
      { names: ['Tromsø', 'Tromso'], lat: 69.65, lng: 18.96, label: 'Tromsø', level: 'city' },
      { names: ['Kirkenes'], lat: 69.73, lng: 30.05, label: 'Kirkenes', level: 'city' },
      { names: ['Reykjavik', 'Reykjavík'], lat: 64.15, lng: -21.94, label: 'Reykjavik', level: 'city' },
      { names: ['Iqaluit'], lat: 63.75, lng: -68.52, label: 'Iqaluit', level: 'city' },
      { names: ['Yellowknife'], lat: 62.45, lng: -114.37, label: 'Yellowknife', level: 'city' },
      { names: ['Whitehorse'], lat: 60.72, lng: -135.05, label: 'Whitehorse', level: 'city' },
      { names: ['Utqiagvik', 'Barrow'], lat: 71.29, lng: -156.79, label: 'Utqiagvik', level: 'city' },
      { names: ['Prudhoe Bay'], lat: 70.26, lng: -148.34, label: 'Prudhoe Bay', level: 'city' },
      { names: ['Murmansk'], lat: 68.96, lng: 33.09, label: 'Murmansk', level: 'city' },
      { names: ['Greenland'], lat: 72.0, lng: -40.0, label: 'Greenland', level: 'region' },
      { names: ['Svalbard'], lat: 78.5, lng: 16.0, label: 'Svalbard', level: 'region' },
      { names: ['Bering Strait'], lat: 66.0, lng: -169.0, label: 'Bering Strait', level: 'region' },
    ],
  },
  'us-election': {
    id: 'us-election',
    dir: 'us-election-events',
    // Political-conflict roots only: threats, protests, posture, reduced
    // relations, coercion. Assault/fight roots would flood the wire with
    // ordinary US crime news; those are not policy volatility.
    gdelt: { fips: ['US'], roots: ['13', '14', '15', '16', '17'], defaultGeo: 'United States' },
    actorMap: [
      ['TRUMP|WHITE HOUSE', 'Trump administration'],
      ['DEMOCRAT|BIDEN|HARRIS|NEWSOM|OCASIO|AOC', 'Democrats'],
      ['REPUBLICAN|\\bGOP\\b|CONGRESS', 'Republicans'],
      ['SUPREME COURT|SCOTUS|FEDERAL JUDGE|\\bCOURT\\b', 'Courts'],
    ],
    rssFeeds: [
      { id: 'npr-politics', theatre: 'us-election', name: 'NPR', url: 'https://feeds.npr.org/1014/rss.xml' },
      { id: 'eac', theatre: 'us-election', name: 'EAC', url: 'https://www.eac.gov/rss.xml' },
      gnews('gnews-election', 'us-election', 'US election Trump 2028'),
      gnews('gnews-policy', 'us-election', 'Trump tariffs executive order'),
    ],
    reliefwebIso3: ['usa'],
    osm: { countryCodes: ['us'], bbox: [17.0, -180.0, 72.0, -64.0] },
    outletsToStrip: [],
    gazetteer: [
      { names: ['Washington', 'Washington DC', 'Washington D.C.'], lat: 38.9, lng: -77.04, label: 'Washington', level: 'city', capital: true },
      { names: ['New York'], lat: 40.71, lng: -74.0, label: 'New York', level: 'city' },
      { names: ['Los Angeles'], lat: 34.05, lng: -118.24, label: 'Los Angeles', level: 'city' },
      { names: ['Chicago'], lat: 41.88, lng: -87.63, label: 'Chicago', level: 'city' },
      { names: ['Houston'], lat: 29.76, lng: -95.37, label: 'Houston', level: 'city' },
      { names: ['Phoenix'], lat: 33.45, lng: -112.07, label: 'Phoenix', level: 'city' },
      { names: ['Philadelphia'], lat: 39.95, lng: -75.17, label: 'Philadelphia', level: 'city' },
      { names: ['Atlanta'], lat: 33.75, lng: -84.39, label: 'Atlanta', level: 'city' },
      { names: ['Detroit'], lat: 42.33, lng: -83.05, label: 'Detroit', level: 'city' },
      { names: ['Milwaukee'], lat: 43.04, lng: -87.91, label: 'Milwaukee', level: 'city' },
      { names: ['Pittsburgh'], lat: 40.44, lng: -79.99, label: 'Pittsburgh', level: 'city' },
      { names: ['Las Vegas'], lat: 36.17, lng: -115.14, label: 'Las Vegas', level: 'city' },
      { names: ['Madison'], lat: 43.07, lng: -89.4, label: 'Madison', level: 'city' },
      { names: ['Raleigh'], lat: 35.78, lng: -78.64, label: 'Raleigh', level: 'city' },
      { names: ['Harrisburg'], lat: 40.27, lng: -76.88, label: 'Harrisburg', level: 'city' },
    ],
  },
};

export const THEATRE_IDS = Object.keys(THEATRES);

export function getTheatre(id) {
  const t = THEATRES[id];
  if (!t) throw new Error(`unknown theatre "${id}" (expected one of: ${THEATRE_IDS.join(', ')})`);
  return t;
}
