// Ukraine war gazetteer for headline geocoding. Coordinates for shared names
// are VERBATIM from the site's fix-event-geo-sources.mjs so live-wire dots
// land on the same points as the curated archive. Levels: city = settlement
// point, region = oblast/peninsula-level placement (approximate by design).
// { names: [canonical, ...variants], lat, lng, label, level }

export const UKRAINE_GAZETTEER = [
  // --- oblast capitals + major cities (site-script coords, verbatim) ---
  { names: ['Odesa', 'Odessa'], lat: 46.48, lng: 30.73, label: 'Odesa', level: 'city' },
  { names: ['Mykolaiv', 'Nikolaev', 'Nikolayev'], lat: 46.98, lng: 31.99, label: 'Mykolaiv', level: 'city' },
  { names: ['Kherson'], lat: 46.64, lng: 32.62, label: 'Kherson', level: 'city' },
  { names: ['Zaporizhzhia', 'Zaporizhia', 'Zaporozhye'], lat: 47.84, lng: 35.14, label: 'Zaporizhzhia', level: 'city' },
  { names: ['Donetsk'], lat: 48.02, lng: 37.8, label: 'Donetsk', level: 'city' },
  { names: ['Luhansk', 'Lugansk'], lat: 48.57, lng: 39.3, label: 'Luhansk', level: 'city' },
  { names: ['Kharkiv', 'Kharkov'], lat: 49.99, lng: 36.23, label: 'Kharkiv', level: 'city' },
  { names: ['Dnipro', 'Dnepropetrovsk'], lat: 48.46, lng: 35.05, label: 'Dnipro', level: 'city' },
  { names: ['Kyiv', 'Kiev', 'Kyïv'], lat: 50.45, lng: 30.52, label: 'Kyiv', level: 'city' },
  { names: ['Lviv', 'Lvov', 'Lemberg'], lat: 49.84, lng: 24.03, label: 'Lviv', level: 'city' },
  { names: ['Vinnytsia', 'Vinnitsa'], lat: 49.23, lng: 28.48, label: 'Vinnytsia', level: 'city' },
  { names: ['Sumy'], lat: 50.91, lng: 34.8, label: 'Sumy', level: 'city' },
  { names: ['Chernihiv', 'Chernigov'], lat: 51.49, lng: 31.29, label: 'Chernihiv', level: 'city' },
  { names: ['Poltava'], lat: 49.59, lng: 34.55, label: 'Poltava', level: 'city' },
  { names: ['Cherkasy'], lat: 49.44, lng: 32.06, label: 'Cherkasy', level: 'city' },
  { names: ['Kropyvnytskyi', 'Kirovograd'], lat: 48.51, lng: 32.26, label: 'Kropyvnytskyi', level: 'city' },
  { names: ['Zhytomyr', 'Zhitomir'], lat: 50.25, lng: 28.66, label: 'Zhytomyr', level: 'city' },
  { names: ['Khmelnytskyi', 'Khmelnitsky'], lat: 49.42, lng: 26.99, label: 'Khmelnytskyi', level: 'city' },
  { names: ['Ternopil', 'Ternopol'], lat: 49.55, lng: 25.59, label: 'Ternopil', level: 'city' },
  { names: ['Ivano-Frankivsk', 'Ivano-Frankovsk'], lat: 48.92, lng: 24.71, label: 'Ivano-Frankivsk', level: 'city' },
  { names: ['Uzhhorod', 'Uzhgorod'], lat: 48.62, lng: 22.3, label: 'Uzhhorod', level: 'city' },
  { names: ['Chernivtsi', 'Chernovtsy'], lat: 48.29, lng: 25.94, label: 'Chernivtsi', level: 'city' },
  { names: ['Rivne', 'Rovno'], lat: 50.62, lng: 26.25, label: 'Rivne', level: 'city' },
  { names: ['Lutsk'], lat: 50.75, lng: 25.34, label: 'Lutsk', level: 'city' },
  { names: ['Simferopol'], lat: 44.95, lng: 34.1, label: 'Simferopol', level: 'city' },
  { names: ['Sevastopol'], lat: 44.62, lng: 33.53, label: 'Sevastopol', level: 'city' },
  // --- frontline towns (site-script coords, verbatim) ---
  { names: ['Bakhmut'], lat: 48.59, lng: 38.0, label: 'Bakhmut', level: 'city' },
  { names: ['Avdiivka', 'Avdeevka'], lat: 48.14, lng: 37.74, label: 'Avdiivka', level: 'city' },
  { names: ['Pokrovsk'], lat: 48.28, lng: 37.18, label: 'Pokrovsk', level: 'city' },
  { names: ['Kupiansk', 'Kupyansk'], lat: 49.71, lng: 37.62, label: 'Kupiansk', level: 'city' },
  { names: ['Kurakhove', 'Kurakhovo'], lat: 47.99, lng: 37.28, label: 'Kurakhove', level: 'city' },
  { names: ['Chasiv Yar', 'Chasov Yar'], lat: 48.37, lng: 37.86, label: 'Chasiv Yar', level: 'city' },
  { names: ['Toretsk'], lat: 48.4, lng: 37.85, label: 'Toretsk', level: 'city' },
  { names: ['Kramatorsk'], lat: 48.73, lng: 37.56, label: 'Kramatorsk', level: 'city' },
  { names: ['Sloviansk', 'Slavyansk'], lat: 48.85, lng: 37.6, label: 'Sloviansk', level: 'city' },
  { names: ['Vuhledar', 'Ugledar'], lat: 47.79, lng: 37.26, label: 'Vuhledar', level: 'city' },
  { names: ['Kreminna', 'Kremennaya'], lat: 49.04, lng: 38.22, label: 'Kreminna', level: 'city' },
  { names: ['Siversk', 'Seversk'], lat: 48.86, lng: 38.09, label: 'Siversk', level: 'city' },
  { names: ['Lyman'], lat: 48.99, lng: 37.8, label: 'Lyman', level: 'city' },
  { names: ['Velyka Novosilka'], lat: 47.87, lng: 37.53, label: 'Velyka Novosilka', level: 'city' },
  { names: ['Sudzha'], lat: 51.19, lng: 35.27, label: 'Sudzha', level: 'city' },
  { names: ['Belgorod'], lat: 50.6, lng: 36.59, label: 'Belgorod', level: 'city' },
  { names: ['Kursk'], lat: 51.73, lng: 36.19, label: 'Kursk', level: 'city' },
  { names: ['Tokmak'], lat: 47.25, lng: 35.23, label: 'Tokmak', level: 'city' },
  { names: ['Melitopol'], lat: 46.85, lng: 35.37, label: 'Melitopol', level: 'city' },
  { names: ['Mariupol'], lat: 47.1, lng: 37.56, label: 'Mariupol', level: 'city' },
  { names: ['Berdiansk', 'Berdyansk'], lat: 46.75, lng: 36.8, label: 'Berdiansk', level: 'city' },
  { names: ['Henichesk', 'Genichesk'], lat: 46.17, lng: 34.81, label: 'Henichesk', level: 'city' },
  { names: ['Nova Kakhovka'], lat: 46.75, lng: 33.37, label: 'Nova Kakhovka', level: 'city' },
  { names: ['Enerhodar', 'Energodar'], lat: 47.5, lng: 34.66, label: 'Enerhodar', level: 'city' },
  { names: ['Kostiantynivka', 'Konstantinovka'], lat: 48.53, lng: 37.7, label: 'Kostiantynivka', level: 'city' },
  { names: ['Selydove', 'Selidovo'], lat: 48.15, lng: 37.3, label: 'Selydove', level: 'city' },
  { names: ['Huliaipole', 'Gulyai-Pole', 'Guliaipole'], lat: 47.66, lng: 36.28, label: 'Huliaipole', level: 'city' },
  { names: ['Orikhiv', 'Orekhov'], lat: 47.57, lng: 35.79, label: 'Orikhiv', level: 'city' },
  { names: ['Vasylivka', 'Vasilievka'], lat: 47.43, lng: 35.29, label: 'Vasylivka', level: 'city' },
  { names: ['Beryslav', 'Berislav'], lat: 46.84, lng: 33.42, label: 'Beryslav', level: 'city' },
  // --- Russian war-relevant cities (new for live headlines) ---
  { names: ['Moscow'], lat: 55.76, lng: 37.62, label: 'Moscow', level: 'city' },
  { names: ['Bryansk'], lat: 53.24, lng: 34.37, label: 'Bryansk', level: 'city' },
  { names: ['Voronezh'], lat: 51.66, lng: 39.18, label: 'Voronezh', level: 'city' },
  { names: ['Rostov-on-Don', 'Rostov'], lat: 47.24, lng: 39.72, label: 'Rostov-on-Don', level: 'city' },
  { names: ['Krasnodar'], lat: 45.04, lng: 38.98, label: 'Krasnodar', level: 'city' },
  { names: ['Volgograd'], lat: 48.71, lng: 44.52, label: 'Volgograd', level: 'city' },
  // --- Crimea (new) ---
  { names: ['Feodosia', 'Feodosiya'], lat: 45.03, lng: 35.38, label: 'Feodosia', level: 'city' },
  { names: ['Yalta'], lat: 44.5, lng: 34.17, label: 'Yalta', level: 'city' },
  { names: ['Kerch'], lat: 45.36, lng: 36.47, label: 'Kerch', level: 'city' },
  { names: ['Dzhankoi', 'Dzhankoy'], lat: 45.71, lng: 34.39, label: 'Dzhankoi', level: 'city' },
  { names: ['Yevpatoria'], lat: 45.2, lng: 33.37, label: 'Yevpatoria', level: 'city' },
  { names: ['Kakhovka'], lat: 46.81, lng: 33.47, label: 'Kakhovka', level: 'city' },
  // --- more Ukrainian cities/towns in war headlines (new) ---
  { names: ['Kryvyi Rih', 'Krivoy Rog'], lat: 47.91, lng: 33.39, label: 'Kryvyi Rih', level: 'city' },
  { names: ['Bila Tserkva'], lat: 49.8, lng: 30.12, label: 'Bila Tserkva', level: 'city' },
  { names: ['Nikopol'], lat: 47.57, lng: 34.4, label: 'Nikopol', level: 'city' },
  { names: ['Izium', 'Izyum'], lat: 49.21, lng: 37.25, label: 'Izium', level: 'city' },
  { names: ['Vovchansk', 'Volchansk'], lat: 50.29, lng: 36.94, label: 'Vovchansk', level: 'city' },
  { names: ['Robotyne'], lat: 47.45, lng: 35.85, label: 'Robotyne', level: 'city' },
  { names: ['Soledar'], lat: 48.7, lng: 38.07, label: 'Soledar', level: 'city' },
  { names: ['Svatove', 'Svatovo'], lat: 49.41, lng: 38.16, label: 'Svatove', level: 'city' },
  { names: ['Lysychansk', 'Lisichansk'], lat: 48.92, lng: 38.43, label: 'Lysychansk', level: 'city' },
  { names: ['Sievierodonetsk', 'Severodonetsk'], lat: 48.95, lng: 38.49, label: 'Sievierodonetsk', level: 'city' },
  { names: ['Rubizhne', 'Rubezhnoye'], lat: 49.02, lng: 38.38, label: 'Rubizhne', level: 'city' },
  { names: ['Marinka', 'Maryinka'], lat: 47.95, lng: 37.5, label: 'Marinka', level: 'city' },
  { names: ['Krasnohorivka', 'Krasnogorovka'], lat: 47.99, lng: 37.62, label: 'Krasnohorivka', level: 'city' },
  { names: ['Ocheretyne', 'Ocheretino'], lat: 48.24, lng: 37.61, label: 'Ocheretyne', level: 'city' },
  { names: ['Novohrodivka', 'Novogrodovka'], lat: 48.16, lng: 37.34, label: 'Novohrodivka', level: 'city' },
  { names: ['Myrnohrad'], lat: 48.29, lng: 37.27, label: 'Myrnohrad', level: 'city' },
  { names: ['Dobropillia'], lat: 48.47, lng: 37.08, label: 'Dobropillia', level: 'city' },
  { names: ['Druzhkivka', 'Druzhkovka'], lat: 48.62, lng: 37.53, label: 'Druzhkivka', level: 'city' },
  { names: ['Borova', 'Borovaya'], lat: 49.37, lng: 37.73, label: 'Borova', level: 'city' },
  { names: ['Sviatohirsk', 'Svyatogorsk'], lat: 49.03, lng: 37.56, label: 'Sviatohirsk', level: 'city' },
  { names: ['Stanytsia Luhanska'], lat: 48.66, lng: 39.47, label: 'Stanytsia Luhanska', level: 'city' },
  { names: ['Popasna', 'Popasnaya'], lat: 48.63, lng: 38.38, label: 'Popasna', level: 'city' },
  { names: ['Shchastia', 'Schastia', 'Schastye'], lat: 48.74, lng: 39.22, label: 'Shchastia', level: 'city' },
  // --- oblast names differing from their capital (placed at capital, region level) ---
  { names: ['Kirovohrad'], lat: 48.51, lng: 32.26, label: 'Kirovohrad region', level: 'region' },
  { names: ['Volyn'], lat: 50.75, lng: 25.34, label: 'Volyn region', level: 'region' },
  { names: ['Zakarpattia', 'Transcarpathia'], lat: 48.62, lng: 22.3, label: 'Zakarpattia region', level: 'region' },
  { names: ['Dnipropetrovsk'], lat: 48.46, lng: 35.05, label: 'Dnipropetrovsk region', level: 'region' },
  // --- named war regions (approximate by design) ---
  { names: ['Donbas', 'Donbass', 'Donets Basin'], lat: 48.3, lng: 38.3, label: 'Donbas', level: 'region' },
  { names: ['Crimea', 'Crimean'], lat: 45.3, lng: 34.4, label: 'Crimea', level: 'region' },
];

// Deliberately NOT included (false-positive or unmappable hazards):
// - 'Moskva' (also the sunk cruiser), bare country names (Russia/Ukraine),
//   rivers (Dnipro/Dnieper, Donets), seas (Black Sea), alliances (NATO/EU).
